### ISSUE TITLE
Consider using basic DEFLATE in release zip packages

### ISSUE THREAD

**Issue by direvus** [hydroffice/hyo2_qc#2]
The current release QCTools.3.5.13.zip uses the DEFLATE64 compression algorithm, which some zip tools do not support.

Please consider packaging future releases using basic DEFLATE for compression, which is understood by all zip tools.  It is slightly less efficient compression (around 10%) but that seems like a fair enough price to pay, for broad compatibility.

Thank you for your time.

**Comment by giumas** [comment]
Implemented.

**Comment by direvus** [comment]
Thank you!  Much appreciated.
